### Testar /
GET http://localhost:3333 HTTP/1.1

### test extension
GET https://www.google.com/ HTTP/1.1

### Consulta USUÀRIO
POST http://localhost:3333/users/login HTTP/1.1
content-type: application/json

{
  "name": "glpi.hcufpe",
  "password": "ebserh@123"
}

### Get RMA
GET http://localhost:3333/RMA
Authorization: "BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2xwaS5oY3VmcGUiLCJncm91cHMiOlsiRGVuaWVkIFJPREMgUGFzc3dvcmQgUmVwbGljYXRpb24gR3JvdXAiLCJEaXN0cmlidXRlZCBDT00gVXNlcnMiLCJFdmVudCBMb2cgUmVhZGVycyIsIkdMTy1TRUMtRUJTRVJILUFETUlOSVNUUkFUT1IiLCJHTE8tU0VDLUhDUEUtQURNSU5JU1RSQVRPUiIsIkdMTy1TRUMtSFVTLVJFUE8iLCJHTE8tU0VDLVNFREUtQ09OVEFTLVNFUlZJQ08iLCJHcm91cCBQb2xpY3kgQ3JlYXRvciBPd25lcnMiLCJQZXJmb3JtYW5jZSBMb2cgVXNlcnMiXSwiaWF0IjoxNjM4Mzc4NjkyLCJleHAiOjE2MzgzNzg2OTJ9.cERzlbj28zzqS-PfMLVJ94W-ATB315ZBUczcFbXgrMw"