SELECT
  TO_CHAR(PROCEDIMENTOS.dt_consulta,
         'YYYYMMDD') AS DATA_PROCEDIMENTO,
       PROCEDIMENTOS.NUMERO AS NUM_CONSULTA,
       PROCEDIMENTOS.PAC_CODIGO,
      SERVIDORES_CNS.VALOR AS CNS,
       SERVIDORES_INFO.NOME AS PROFISSIONAL_NOME,
       SERVIDORES_CBO1.VALOR AS CBO,
       PACIENTES.NRO_CARTAO_SAUDE AS PACIENTE_CARTAO_SUS,
       PACIENTES.NOME AS PACIENTE_NOME,
       PACIENTES.SEXO_BIOLOGICO AS PACIENTE_SEXO_BIOLOGICO,
       TO_CHAR(PACIENTES.DT_NASCIMENTO,
         'YYYYMMDD') AS PACIENTE_DATA_NASCIMENTO,
       PACIENTES.NAC_CODIGO AS PACIENTE_NACIONALIDADE,
CASE
           WHEN CIDADES.COD_IBGE IS NULL THEN CIDADES2.COD_IBGE::text
            ELSE CIDADES.COD_IBGE::text
             END AS CIDADE,
       CASE
           WHEN PACIENTES.COR = 'B' THEN '01'
            WHEN PACIENTES.COR = 'P' THEN '02'
            WHEN PACIENTES.COR = 'M' THEN '03'
            WHEN PACIENTES.COR = 'A' THEN '04'
            WHEN PACIENTES.COR = 'I' THEN '05'
            ELSE '99'
             END AS PACIENTE_COR,
       CASE
           WHEN PACIENTES_ENDERECO.CEP IS NULL THEN PACIENTES_ENDERECO.BCL_CLO_CEP
            ELSE PACIENTES_ENDERECO.CEP
             END AS CEP,
       TIPO_LOGRADOUROS.CODIGO_BASE_SUS AS COD_LOGRADOURO,
       '' as CID,
       1 AS PROCEDIMENTO_QUANTIDADE,
 CASE
    WHEN SERVIDORES_CBO1.valor like '2231%' THEN 0301010072
    WHEN SERVIDORES_CBO1.valor like '2251%' THEN 0301010072
    WHEN SERVIDORES_CBO1.valor like '2252%' THEN 0301010072
    WHEN SERVIDORES_CBO1.valor like '2253%' THEN 0301010072
    ELSE 0301010048
  END as procedimento_sus,

       CASE
           WHEN CIDADES.UF_SIGLA IS NOT NULL THEN CIDADES.UF_SIGLA
            ELSE CIDADES2.UF_SIGLA
             END AS UF,
       CASE
           WHEN PACIENTES_ENDERECO.LOGRADOURO IS NOT NULL THEN PACIENTES_ENDERECO.LOGRADOURO
            ELSE LOGRADOUROS.NOME
             END AS LOGRADOURO,
       PACIENTES_ENDERECO.NRO_LOGRADOURO AS NRO,
       PACIENTES_ENDERECO.COMPL_LOGRADOURO AS COMPLEMENTO,
       BAIRROS.descricao AS BAIRRO,
       'CONSULTAS' AS TIPO_REGISTRO
from
agh.aac_consultas as PROCEDIMENTOS -- Informações da Grade
LEFT OUTER JOIN AGH.AIP_PACIENTES AS PACIENTES
    ON PACIENTES.CODIGO = PROCEDIMENTOS.PAC_CODIGO
LEFT JOIN agh.rap_servidores as servidores on servidores.matricula = (
      CASE
        WHEN PROCEDIMENTOS.ser_matricula_atendido IS NOT NULL THEN PROCEDIMENTOS.ser_matricula_atendido
        WHEN PROCEDIMENTOS.ser_matricula_alterado IS NOT NULL THEN PROCEDIMENTOS.ser_matricula_alterado
        WHEN PROCEDIMENTOS.ser_matricula_consultado IS NOT NULL THEN PROCEDIMENTOS.ser_matricula_consultado
        WHEN PROCEDIMENTOS.ser_matricula IS NOT NULL THEN PROCEDIMENTOS.ser_matricula
        ELSE NULL
      END
    )
    AND servidores.vin_codigo = (
      CASE
        WHEN PROCEDIMENTOS.ser_matricula_atendido IS NOT NULL THEN PROCEDIMENTOS.ser_vin_codigo_atendido
        WHEN PROCEDIMENTOS.ser_matricula_alterado IS NOT NULL THEN PROCEDIMENTOS.ser_vin_codigo_alterado
        WHEN PROCEDIMENTOS.ser_matricula_consultado IS NOT NULL THEN PROCEDIMENTOS.ser_vin_codigo_consultado
        WHEN PROCEDIMENTOS.ser_matricula IS NOT NULL THEN PROCEDIMENTOS.ser_vin_codigo
        ELSE NULL
      END
    ) 
  LEFT OUTER JOIN AGH.RAP_PESSOA_TIPO_INFORMACOES SERVIDORES_CNS
    ON SERVIDORES_CNS.PES_CODIGO = SERVIDORES.PES_CODIGO
   AND SERVIDORES_CNS.TII_SEQ = 7
  LEFT OUTER JOIN AGH.RAP_PESSOA_TIPO_INFORMACOES SERVIDORES_CBO1
    ON SERVIDORES_CBO1.PES_CODIGO = SERVIDORES.PES_CODIGO
   AND SERVIDORES_CBO1.TII_SEQ = 2
  LEFT OUTER JOIN AGH.RAP_PESSOA_TIPO_INFORMACOES SERVIDORES_CBO2
    ON SERVIDORES_CBO2.PES_CODIGO = SERVIDORES.PES_CODIGO
   AND SERVIDORES_CBO2.TII_SEQ = 2
 LEFT OUTER JOIN AGH.RAP_PESSOAS_FISICAS AS SERVIDORES_INFO
    ON SERVIDORES_INFO.CODIGO = SERVIDORES.PES_CODIGO
  LEFT OUTER JOIN AGH.AIP_ENDERECOS_PACIENTES PACIENTES_ENDERECO
    ON PACIENTES.CODIGO = PACIENTES_ENDERECO.PAC_CODIGO
   AND PACIENTES_ENDERECO.TIPO_ENDERECO = 'R'
  AND SERVIDORES_CBO2.TII_SEQ = 3
LEFT OUTER JOIN AGH.AIP_CIDADES AS CIDADES
    ON PACIENTES_ENDERECO.CDD_CODIGO = CIDADES.CODIGO
  LEFT OUTER JOIN AGH.AIP_CEP_LOGRADOUROS AS CEP
    ON CEP.CEP = 
      (CASE
        WHEN PACIENTES_ENDERECO.CEP IS NOT NULL THEN PACIENTES_ENDERECO.CEP
        ELSE PACIENTES_ENDERECO.BCL_CLO_CEP
      END)
  LEFT OUTER JOIN AGH.AIP_LOGRADOUROS AS LOGRADOUROS
    ON LOGRADOUROS.CODIGO = CEP.LGR_CODIGO
  LEFT OUTER JOIN AGH.AIP_CIDADES AS CIDADES2
    ON CIDADES2.CODIGO = LOGRADOUROS.CDD_CODIGO
  LEFT OUTER JOIN AGH.AIP_TIPO_LOGRADOUROS AS TIPO_LOGRADOUROS
    ON TIPO_LOGRADOUROS.CODIGO = LOGRADOUROS.TLG_CODIGO
  LEFT OUTER JOIN AGH.AIP_BAIRROS_CEP_LOGRADOURO as BAIRROS_CEP ON
    (CASE
        WHEN PACIENTES_ENDERECO.CEP IS NOT NULL THEN PACIENTES_ENDERECO.CEP
        ELSE PACIENTES_ENDERECO.BCL_CLO_CEP
    END) = BAIRROS_CEP.clo_cep
  LEFT OUTER JOIN AGH.aip_bairros as BAIRROS ON
    BAIRROS.codigo = BAIRROS_CEP.bai_codigo
 
WHERE
dt_consulta between '#startDate 00:00:00' AND '#endDate 23:59:59.999999'
and PROCEDIMENTOS.ret_seq = 10
and PROCEDIMENTOS.pac_codigo <> 1000001
and PROCEDIMENTOS.grd_seq NOT IN (582, 579, 1488, 1782, 1972, 1970, 1974, 1968, 1976, 1958, 1977, 1980, 1978, 1982, 1983, 2034, 1994, 1988, 2016, 1992, 2036, 1998, 2000, 2002, 2006, 2005, 1996, 2004, 2014, 2030, 2032, 2038, 2040, 2039, 2037)
