SELECT
  reg.CD_MATERIAL           AS "Código Master"
  ,round(avg(reg.VL_MATERIAL / reg.QT_MATERIAL), 2) AS "Valor Unitário"
FROM HUMASTER.VTB_REGISTRO_LICITACAO lic
LEFT JOIN HUMASTER.TB_REGISTRO_LICITACAO_MATERIAL reg 
  ON lic.NU_REGISTRO_LICITACAO  = reg.NU_REGISTRO_LICITACAO
  AND lic.DT_FIM_VIGENCIA >= trunc(CURRENT_DATE, 'day')
LEFT JOIN humaster.TB_MATERIAL mat  
  ON mat.CD_MATERIAL        = reg.CD_MATERIAL
WHERE reg.cd_material IS NOT NULL
GROUP BY reg.CD_MATERIAL
ORDER BY 1
